### ISSUE TITLE
Recirculation of every site

### ISSUE THREAD

**Issue by neurosnap** [michigan-com/dashbeat#26]
Data for recirculation by site is located in `quickstats`

**Comment by bendik** [comment]
We could merge this and improve the styling a little but we talked it over and it seems a little too unclear what this dashboard say. Having every publishers recirculation displayed next to each other is an improvement however. So i'm thinking it'd be best if we took the current recirculation dashboard and improve it. A few ways it could do this and more would be:

- Create a guage for each publisher
- Preserve it's current styling putting it under a `:only-child` selector and use some content-length selectors flex-order to customize layout based on publisher count
- Take a single or multiple publishers with `?publisher=freep detroitnews` and filter to only those
- Feel free to use layout styling from the loyalty dashboard to place 7 guages

This can be a nice exercise in creating reusable selectors that filter data based on a subset of publishers

I'm just thinking it's better to have our dashboards support a few paramaters to adjust the same data, than adding to many dashboards. Since we've been playing with the idea of adding controls for selecting publications that will set these parameters and apply them though all the dashboards in the slideshow.

**Comment by neurosnap** [comment]
Agreed, I can see how comparing these markets' recirculation doesn't really provide meaningful data.  My initial guess is that recirculation is going to be correlated to viewers.

What might be more interesting is to be able to detect when recirculation increases for a site and then highlight that on the dashboard.

**Comment by travelinreid** [comment]
Nope. 

I want to see the recirc of all sites at the same time, in real time.
